#!/usr/bin/env python3
"""Extract requested option 1m bars from iFinD wide Excel exports.

Input workbooks are the wide iFinD sheets exported as repeated 15-column
contract blocks:

    code, name, ..., then row 3 fields date/time/open/high/low/close/...

This script reads a requirements CSV generated by
``build_v12_option_cache_requirements.py`` and writes only the requested
``data/intraday_cache/YYYY-MM-DD_########_1m.csv`` files.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import re
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from zipfile import ZipFile

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
WIDE_DIR = DATA / "双创补充期权数据"
INTRADAY_CACHE = DATA / "intraday_cache"
RESEARCH = ROOT / "research"

EXCEL_BASE = dt.datetime(1899, 12, 30)
BLOCK_WIDTH = 15
FIELD_OFFSETS = {
    "date": 0,
    "time": 1,
    "open": 2,
    "high": 3,
    "low": 4,
    "close": 5,
    "volume": 6,
    "amount": 7,
    "change_ratio": 9,
}


@dataclass(frozen=True)
class WorkbookSpec:
    underlying: str
    path: Path
    start: str
    end: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--requirements",
        type=Path,
        default=RESEARCH / "v12_option_cache_requirements.csv",
    )
    parser.add_argument("--wide-dir", type=Path, default=WIDE_DIR)
    parser.add_argument("--cache-dir", type=Path, default=INTRADAY_CACHE)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit-files", type=int, default=0)
    parser.add_argument(
        "--summary",
        type=Path,
        default=RESEARCH / "v12_ifind_wide_cache_extract_summary.csv",
    )
    return parser.parse_args()


def normalize_code(value: Any) -> str:
    text = str(value).strip()
    text = text.split(".")[0]
    digits = "".join(ch for ch in text if ch.isdigit())
    return digits.zfill(8) if digits else ""


def col_to_num(ref: str) -> int:
    letters = "".join(ch for ch in ref if ch.isalpha())
    value = 0
    for ch in letters:
        value = value * 26 + ord(ch.upper()) - 64
    return value


def shared_strings(zf: ZipFile) -> list[str]:
    if "xl/sharedStrings.xml" not in zf.namelist():
        return []
    values: list[str] = []
    with zf.open("xl/sharedStrings.xml") as fh:
        for _, element in ET.iterparse(fh, events=("end",)):
            if element.tag.endswith("}si"):
                values.append(
                    "".join(
                        node.text or ""
                        for node in element.iter()
                        if node.tag.endswith("}t")
                    )
                )
                element.clear()
    return values


def cell_value(cell: ET.Element, strings: list[str]) -> str | None:
    value = None
    for child in cell:
        if child.tag.endswith("}v"):
            value = child.text
            break
    if value is None:
        return None
    if cell.attrib.get("t") == "s":
        try:
            return strings[int(value)]
        except Exception:
            return value
    return value


def excel_date(value: Any) -> str | None:
    try:
        number = float(value)
    except Exception:
        text = str(value).strip()
        parsed = pd.to_datetime(text, errors="coerce")
        if pd.isna(parsed):
            return None
        return parsed.strftime("%Y-%m-%d")
    return (EXCEL_BASE + dt.timedelta(days=number)).strftime("%Y-%m-%d")


def excel_datetime(date_value: Any, time_value: Any) -> str | None:
    date_text = excel_date(date_value)
    if date_text is None:
        return None
    try:
        fraction = float(time_value)
    except Exception:
        time_text = str(time_value).strip()
        parsed = pd.to_datetime(f"{date_text} {time_text}", errors="coerce")
        if pd.isna(parsed):
            return None
        return parsed.strftime("%Y-%m-%d %H:%M:%S")
    full = pd.Timestamp(EXCEL_BASE + dt.timedelta(days=float(date_value) + fraction))
    return full.strftime("%Y-%m-%d %H:%M:%S")


def to_float(value: Any) -> float | None:
    try:
        return float(value)
    except Exception:
        return None


def discover_workbooks(wide_dir: Path) -> list[WorkbookSpec]:
    specs: list[WorkbookSpec] = []
    for path in sorted(wide_dir.glob("*.xlsx")):
        name = path.name
        underlying = "159915" if "创业板" in name else "588000" if "科创50" in name else ""
        dates = re.findall(r"20\d{6}", name)
        if not underlying or not dates:
            continue
        start = pd.Timestamp(dates[0]).strftime("%Y-%m-%d")
        if len(dates) >= 2 and dates[1].startswith("2020") and len(dates[1]) == 8:
            # Preserve odd file-name typos like 202050731 by using a broad
            # upper bound; actual rows are still filtered by requirements.
            end = "2025-12-31"
        elif len(dates) >= 2:
            end = pd.Timestamp(dates[1]).strftime("%Y-%m-%d")
        elif "20250101" in name:
            end = "2025-12-31"
        else:
            end = "2099-12-31"
        specs.append(WorkbookSpec(underlying=underlying, path=path, start=start, end=end))
    return specs


def load_requirements(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    req = pd.read_csv(path, dtype={"option_code": str, "underlying_code": str})
    if req.empty:
        return req
    req["trade_date"] = pd.to_datetime(req["trade_date"]).dt.strftime("%Y-%m-%d")
    req["underlying_code"] = req["underlying_code"].astype(str).str.split(".").str[0]
    req["option_code"] = req["option_code"].map(normalize_code)
    return req.drop_duplicates(["trade_date", "underlying_code", "option_code"])


def workbook_tasks(req: pd.DataFrame, specs: list[WorkbookSpec]) -> dict[Path, dict[str, set[str]]]:
    tasks: dict[Path, dict[str, set[str]]] = {}
    for spec in specs:
        rows = req[
            (req["underlying_code"] == spec.underlying)
            & (req["trade_date"] >= spec.start)
            & (req["trade_date"] <= spec.end)
        ]
        if rows.empty:
            continue
        mapping: dict[str, set[str]] = defaultdict(set)
        for row in rows.itertuples(index=False):
            mapping[str(row.option_code)].add(str(row.trade_date))
        tasks[spec.path] = mapping
    return tasks


def row_cells(row: ET.Element, strings: list[str], wanted_cols: set[int] | None = None) -> dict[int, str]:
    output: dict[int, str] = {}
    for cell in row:
        if not cell.tag.endswith("}c"):
            continue
        ref = cell.attrib.get("r", "")
        col = col_to_num(ref)
        if wanted_cols is not None and col not in wanted_cols:
            continue
        value = cell_value(cell, strings)
        if value is not None:
            output[col] = value
    return output


def build_code_columns(zf: ZipFile, strings: list[str], needed_codes: set[str]) -> dict[str, int]:
    code_to_start: dict[str, int] = {}
    with zf.open("xl/worksheets/sheet1.xml") as fh:
        for _, element in ET.iterparse(fh, events=("end",)):
            if not element.tag.endswith("}row"):
                continue
            if element.attrib.get("r") != "1":
                element.clear()
                continue
            cells = row_cells(element, strings)
            for col, value in cells.items():
                if (col - 1) % BLOCK_WIDTH != 0:
                    continue
                code = normalize_code(value)
                if code in needed_codes:
                    code_to_start[code] = col
            element.clear()
            break
    return code_to_start


def extract_workbook(
    workbook: Path,
    code_dates: dict[str, set[str]],
    cache_dir: Path,
    overwrite: bool,
    dry_run: bool,
) -> dict[str, Any]:
    with ZipFile(workbook) as zf:
        strings = shared_strings(zf)
        code_to_start = build_code_columns(zf, strings, set(code_dates.keys()))
        wanted_cols: set[int] = set()
        col_to_code: dict[int, str] = {}
        for code, start_col in code_to_start.items():
            for offset in FIELD_OFFSETS.values():
                col = start_col + offset
                wanted_cols.add(col)
                col_to_code[col] = code

        rows_by_key: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
        with zf.open("xl/worksheets/sheet1.xml") as fh:
            for _, element in ET.iterparse(fh, events=("end",)):
                if not element.tag.endswith("}row"):
                    continue
                row_number = int(element.attrib.get("r", "0"))
                if row_number < 9 or not wanted_cols:
                    element.clear()
                    continue
                cells = row_cells(element, strings, wanted_cols)
                if not cells:
                    element.clear()
                    continue
                for code, start_col in code_to_start.items():
                    raw_date = cells.get(start_col + FIELD_OFFSETS["date"])
                    raw_time = cells.get(start_col + FIELD_OFFSETS["time"])
                    if raw_date is None or raw_time is None:
                        continue
                    trade_date = excel_date(raw_date)
                    if trade_date not in code_dates[code]:
                        continue
                    timestamp = excel_datetime(raw_date, raw_time)
                    if timestamp is None:
                        continue
                    close_value = to_float(cells.get(start_col + FIELD_OFFSETS["close"]))
                    if close_value is None:
                        continue
                    rows_by_key[(trade_date, code)].append(
                        {
                            "datetime": timestamp,
                            "option_code": code,
                            "open": to_float(cells.get(start_col + FIELD_OFFSETS["open"])),
                            "high": to_float(cells.get(start_col + FIELD_OFFSETS["high"])),
                            "low": to_float(cells.get(start_col + FIELD_OFFSETS["low"])),
                            "close": close_value,
                            "volume": to_float(cells.get(start_col + FIELD_OFFSETS["volume"])) or 0.0,
                            "amount": to_float(cells.get(start_col + FIELD_OFFSETS["amount"])) or 0.0,
                            "change_ratio": to_float(cells.get(start_col + FIELD_OFFSETS["change_ratio"])),
                        }
                    )
                element.clear()

    cache_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    skipped_existing = 0
    empty = 0
    for code, dates in code_dates.items():
        for trade_date in dates:
            key = (trade_date, code)
            out_path = cache_dir / f"{trade_date}_{code}_1m.csv"
            if out_path.exists() and not overwrite:
                skipped_existing += 1
                continue
            records = rows_by_key.get(key, [])
            if not records:
                empty += 1
                continue
            if not dry_run:
                frame = pd.DataFrame(records)
                frame = frame.drop_duplicates(["datetime", "option_code"], keep="last")
                frame = frame.sort_values("datetime")
                frame.to_csv(out_path, index=False, quoting=csv.QUOTE_MINIMAL)
            written += 1
    return {
        "workbook": str(workbook),
        "requested_codes": len(code_dates),
        "matched_codes": len(code_to_start),
        "requested_files": sum(len(v) for v in code_dates.values()),
        "written_files": written,
        "skipped_existing": skipped_existing,
        "empty_files": empty,
        "dry_run": dry_run,
    }


def main() -> None:
    args = parse_args()
    req = load_requirements(args.requirements)
    specs = discover_workbooks(args.wide_dir)
    tasks = workbook_tasks(req, specs)
    if args.limit_files > 0:
        tasks = dict(list(tasks.items())[: args.limit_files])
    summaries: list[dict[str, Any]] = []
    for workbook, code_dates in tasks.items():
        print(
            {
                "workbook": workbook.name,
                "codes": len(code_dates),
                "files": sum(len(v) for v in code_dates.values()),
            },
            flush=True,
        )
        summaries.append(
            extract_workbook(
                workbook,
                code_dates,
                args.cache_dir,
                args.overwrite,
                args.dry_run,
            )
        )
    summary = pd.DataFrame(summaries)
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(args.summary, index=False)
    print(summary.to_string(index=False) if not summary.empty else "no tasks")
    print({"summary": str(args.summary), "workbooks": len(summaries)})


if __name__ == "__main__":
    main()
